Remove `pipefail` bashism from POSIX shell script
Canva/rules_nodejs pull request #42
Opened 2023-12-05 04:28 UTC by Silic0nS0ldier

Issue overlooked due to macOS using `bash` as `sh` (despite also having `dash`).

2023-12-05 06:05 UTC, christianscott requested changes
Why do we need to remove `pipefail`?

2023-12-05 06:05 UTC, christianscott commented on internal/npm_install/bulk_copy.sh
>  #!/bin/sh
missed this on the first PR. why not
```suggestion
#! /usr/bin/env bash
```
?

2023-12-05 06:10 UTC, Silic0nS0ldier commented
> Why do we need to remove pipefail?

Because I wrote the script to use `sh` (POSIX shell) which does not support that option.

The suggestion of outright using `bash` would make it safe though.

2023-12-06 04:19 UTC, christianscott approved these changes
LGTM

2023-12-06 05:28 UTC, merged